# Generated by Django 5.0.6 on 2024-06-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survivor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=40)),
                ('latitute', models.CharField(max_length=120)),
                ('longitude', models.CharField(max_length=120)),
            ],
        ),
    ]
