# Generated by Django 5.0.6 on 2024-06-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zombie_invasion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survivor',
            name='ammunition',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survivor',
            name='food',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survivor',
            name='medication',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survivor',
            name='water',
            field=models.IntegerField(default=0),
        ),
    ]
