# Generated by Django 5.0.6 on 2024-06-24 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zombie_invasion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported', to='zombie_invasion.survivor')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to='zombie_invasion.survivor')),
            ],
        ),
    ]
